# This is autogen file by tools/travis_yml_generator.py
# Do not change it manualy because after a next `git push` command this file
#   will be regenerated.
#

language: cpp

before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq

jobs:
  include:
    - stage: Build && Test && Package
      script: |
              echo "hw1.1-CI_CD_helloworld"
              pushd hw1.1-CI_CD_helloworld
              mkdir build
              cd build
              cmake ..
              cmake --build .
              cmake --build . --target test
              cmake --build . --target package
              popd
